### ISSUE TITLE
sign in fails

### ISSUE THREAD

**Issue by trvrcr** [myTselection/bibliotheek_be#11] opened 2023-02-26 21:08 UTC
When inserting username and password the integration fails.
is it possible to hard code them in the configuration.yaml file?

**Comment by myTselection** [comment] 2023-02-26 22:24
I didn't try via configuration.yaml, but it might work as some code for it exists.
is the login working with your credentials via bibliotheek.be > aanmelden? 
Will test again integration setup in coming days.

**Comment by myTselection** [comment] 2023-02-28 06:10
I was able to reproduce it, but root cause not found yet. Will try to fix asap.

**Comment by myTselection** [comment] 2023-02-28 09:00
fixed by skipping some validation step, will open a separate ticket to further check the input validation

**Closed by myTselection** 2023-02-28 09:00 UTC
